projectLanguage: js
locations:
  base: src
  arguments: arguments
  commands: commands
  listeners: listeners
  preconditions: preconditions
  interaction-handlers: interaction-handlers
  routes: ''
customFileTemplates:
  enabled: false
  location: ''
